1. Creating numpy/n-d array

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])  #List pass kari to array ban gaya
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
#2-dimensional Array
arr2=np.array([[1,2,3],[4,5,6]])  #It is called 2D array necause it has both rows(2) and columns(3)
arr2                               #first row(1,2,3) and second row(4,5,6)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3=np.zeros((2,3))  #It means to create an array of 2 rows and 3 columns with the default value of 0
arr3                  #Update values later as needed, Create initial empty space in an array , Write code that's fast and efficient

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr5=np.identity(4)   #Matrix of 5x5 where every value is 0 except diagonally 1
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr6=np.arange(10) #It will create a range between 0 and 9 (10 elements)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr7=np.arange(4,12,2) #(start,end,jump)
arr7

array([ 4,  6,  8, 10])

In [ ]:
arr7=np.linspace(10,20,10)  #start from 10,end on 20,Total of 10 values,all values will be equally spaced (with equal gaps).
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# **Numpy Properties and Attributes**

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1.shape

(5,)

In [ ]:
arr2.shape

(2, 3)

In [ ]:
# 3-Dimensional Array
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
"""
Think Of it as:
[
  [ [1, 2], [3, 4] ],   # First 2D block
  [ [5, 6], [7, 8] ]    # Second 2D block
]
"""
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr9.shape   #(2,2,2)means 2 blocks,2 rows,2 columns

(2, 2, 2)

In [ ]:
arr9.ndim  #ndim is used to determine dimensions


3

In [ ]:
arr6.ndim

1

In [ ]:
arr1.size

5

In [ ]:
arr8.size

10

In [ ]:
arr5.size


16

In [ ]:
arr5.itemsize  #The size (in bytes) of each element in the array.

8

In [ ]:
arr4.itemsize

8

In [ ]:
arr1.dtype  #dtype is used to determine the datatype

dtype('int64')

In [ ]:
arr9.dtype

dtype('int64')

In [ ]:
arr9.astype('float')   #astype() is used to change the type of each element in the array.

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

# **Indexing,Slicing and Iteration**

In [ ]:
arr12=np.arange(24)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
#Reshape  (Reshape is used to change the shape (rows,columns,dimensions)of an array without changing its data)
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#Sicing
arr12[4]

array([16, 17, 18, 19])

In [ ]:
arr13=arr12[1:4]
arr13

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr14=arr12[:3]
arr14

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr15=np.arange(14).reshape(2,7)
arr15


array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [ ]:
arr15[:,2]   #[:,2] means all rows and 2 indicates the column number

array([2, 9])

In [ ]:
arr15[1:,]   #[1:,] indicates row1 and all columns

array([[ 7,  8,  9, 10, 11, 12, 13]])

In [ ]:
arr15[:,1:3]  #All rows with 1st and 2nd column

array([[1, 2],
       [8, 9]])

In [ ]:
arr15[0:2,1:3]   #0 and 1st row with 1st and 2nd column

array([[1, 2],
       [8, 9]])

In [ ]:
#Iteration
for i in arr12:  #This loops through each row of the array.
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [ ]:
for i in np.nditer(arr12):    #This loops through each element of the array one by one, no matter how many rows/columns it has.
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# **Numpy Operations**


In [ ]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])

In [ ]:
arr1-arr2

array([-6, -6, -6, -6, -6, -6])

In [ ]:
arr1*2   #Scalar Multiplication

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr2>3  #When the condition will satisty It will give true

array([ True,  True,  True,  True,  True,  True])

In [ ]:
arr1<4

array([ True,  True,  True, False, False, False])

In [ ]:
arr3=np.arange(6).reshape(2,3)
arr3



array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr4=np.arange(6,12).reshape(3,2)
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr3.dot(arr4)  #Dot product or Dot Matrix Multiplication

array([[ 28,  31],
       [100, 112]])

In [ ]:
arr3.max()


np.int64(5)

In [ ]:
arr4.min()

np.int64(6)

In [ ]:
arr4.min(axis=0) #axis=0 represents row

array([6, 7])

In [ ]:
arr4.max(axis=1) #axis=1 represents column

array([ 7,  9, 11])

In [ ]:
arr4.sum()  #sum represents the sum of all elements in the array 4

np.int64(51)

In [ ]:
arr4.sum(axis=0)

array([24, 27])

In [ ]:
arr4.mean()

np.float64(8.5)

In [ ]:
arr4.std()    #The purpose of standard deviation is to measure how spread out or close together the values are in a dataset.

np.float64(1.707825127659933)

In [ ]:
np.sin(arr4) #It calculates the sine value for each number in the array.

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [ ]:
np.exp(arr4)  #Exponent

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

# **Reshaping Numpy Array**

In [ ]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr4.ndim

2

In [ ]:
arr4.ravel()  #ravel() is used to convert any array into a 1D array.


array([ 6,  7,  8,  9, 10, 11])

In [ ]:
arr4.transpose()    #row to column and column to row

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [ ]:
arr5=np.arange(12,18).reshape(2,3)  #similar matrix as arr3

In [ ]:
#Horizontal Stack
np.hstack((arr3,arr5))    #It joins arrays in left-to-right direction — like adding more columns.like first three elements of arr3 and arr5 combined



array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [ ]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
#Vertical Stack
np.vstack((arr5,arr3))

array([[12, 13, 14],
       [15, 16, 17],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [ ]:
np.vsplit(arr3,2)   #np.vsplit() splits an array vertically (by rows), creating smaller arrays from top to bottom.

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [ ]:
arr20=np.arange(20).reshape(4,5)
arr20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.vsplit(arr20,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [ ]:
arr100=np.arange(100).reshape(20,5)
arr100

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [ ]:
np.vsplit(arr100,5)   #it means we divide 0-99 numbers in 5 arrays

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]),
 array([[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]]),
 array([[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]])]

# **Fancy Indexing**

In [ ]:
#If we need 1st,3rd and 5th row of an array,Can we extract it through slicing?
#NO!!then,
arr15=np.arange(24).reshape(6,4)
arr15


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr15[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])